name: use_template

description: Allows you to use any Flutter & Dart project as a template with a single line command.

version: 1.0.1

homepage: https://github.com/baranacikgoz/use_template.git

repository: https://github.com/baranacikgoz/use_template.git

issue_tracker: https://github.com/baranacikgoz/use_template/issues

executables:
  use_template:

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dcli: ^4.0.5
  path: ^1.9.0

dev_dependencies:
  test: ^1.25.8
  very_good_analysis: ^6.0.0